import img1 from "../assets/Accessories 1.png";
import img2 from "../assets/Over-the-Counter 1.png";

export const products = [
  {
    id: 1,
    title: "Ray-Ban UV Protection Sunglasses",
    desc: "Protects against harmful UV rays",
    sales: 23,
    quantity: 12,
    category: "Accessories",
    tryAR: true,
    price: 24.0,
    url: img1,
  },
  {
    id: 2,
    title: "Visine Redness Relief",
    desc: "Eye drops for redness and irritation",
    sales: 15,
    quantity: 8,
    category: "Over-the-Counter",
    tryAR: false,
    price: 11.0,
    url: img2,
  },
  {
    id: 3,
    title: "Ray-Ban UV Protection Sunglasses",
    desc: "Protects against harmful UV rays",
    sales: 23,
    quantity: 4,
    category: "Accessories",
    tryAR: true,
    price: 5,
    url: img1,
  },
  {
    id: 4,
    title: "Ray-Ban UV Protection Sunglasses",
    desc: "Protects against harmful UV rays",
    sales: 23,
    quantity: 5,
    category: "Accessories",
    tryAR: true,
    price: 73,
    url: img1,
  },
];

export const users = [
  {
    id: 1,
    username: "Yousof",
    email: "yousof1@gmail.com",
    password: "123456",
    phoneNumber: "0123456789",
    cart: [],
    billsHistory: [],
    appointments: [],
    role: "client",
    cardNumber: "1234567890123456",
    cardExpiry: "12/25",
    cardCVC: "123",
    cardHolder: "Yousof",
    bannInfo: {
      isBanned: false,
      reason: "",
    },
  },
  {
    id: 2,
    username: "Yousof",
    email: "yousof2@gmail.com",
    password: "123456",
    phoneNumber: "0123456789",
    cart: [],
    billsHistory: [],
    appointments: [],
    role: "client",
    cardNumber: "1234567890123456",
    cardExpiry: "12/25",
    cardCVC: "123",
    cardHolder: "Yousof",
    bannInfo: {
      isBanned: false,
      reason: "",
    },
  },
  {
    id: 3,
    username: "Medohas",
    email: "medohas@gmail.com",
    password: "123456",
    phoneNumber: "0123456789",
    cart: [],
    billsHistory: [],
    appointments: [],
    role: "client",
    cardNumber: "1234567890123456",
    cardExpiry: "12/25",
    cardCVC: "123",
    cardHolder: "Medohas",
    bannInfo: {
      isBanned: true,
      reason: "Bad Behavior",
    },
  },
  {
    id: 4,
    username: "Mohrous",
    email: "mahrous@gmail.com",
    password: "123456",
    phoneNumber: "0123456789",
    cart: [],
    billsHistory: [],
    appointments: [],
    role: "client",
    cardNumber: "1234567890123456",
    cardExpiry: "12/25",
    cardCVC: "123",
    cardHolder: "Mahrous",
    bannInfo: {
      isBanned: true,
      reason: "Bad Behavior",
    },
  },
  {
    id: 5,
    username: "Fawzy",
    email: "fawzy@gmail.com",
    password: "123456",
    phoneNumber: "0123456789",
    cart: [],
    billsHistory: [],
    appointments: [],
    role: "client",
    cardNumber: "1234567890123456",
    cardExpiry: "12/25",
    cardCVC: "123",
    cardHolder: "Fawzy",
    bannInfo: {
      isBanned: true,
      reason: "Bad Behavior",
    },
  },
  {
    id: 6,
    username: "Shokry",
    email: "shokry@gmail.com",
    password: "123456",
    phoneNumber: "0123456789",
    cart: [],
    billsHistory: [],
    appointments: [],
    role: "client",
    cardNumber: "1234567890123456",
    cardExpiry: "12/25",
    cardCVC: "123",
    cardHolder: "Shokry",
    bannInfo: {
      isBanned: true,
      reason: "Bad Behavior",
    },
  },
];

export const pannedEmails = [
  {
    email: "mahrous@gmail.com",
    reason: "Bad Behavior",
  },
  {
    email: "fawzy@gmail.com",
    reason: "Bad Behavior",
  },
  {
    email: "medohas@gmail.com",
    reason: "Bad Behavior",
  },
  {
    email: "shokry@gmail.com",
    reason: "Bad Behavior",
  },
];
